// ignore_for_file: constant_identifier_names

part of 'jete_tws_sdk.dart';

abstract class TwsCommand {
  static const int COMMAND_TYPE_REQUEST = 1;
  static const int COMMAND_TYPE_RESPONSE = 2;
  static const int COMMAND_TYPE_NOTIFY = 3;

  static const int COMMAND_EQ = 0x20;
  static const int COMMAND_MUSIC_CONTROL = 0x21;
  static const int COMMAND_KEY = 0x22;
  static const int COMMAND_AUTO_SHUTDOWN = 0x23;
  static const int COMMAND_FACTORY_RESET = 0x24;
  static const int COMMAND_WORK_MODE = 0x25;
  static const int COMMAND_IN_EAR_DETECT = 0x26;
  static const int COMMAND_DEVICE_INFO = 0x27;
  static const int COMMAND_NOTIFY = 0x28;
  static const int COMMAND_LANGUAGE = 0x29;
  static const int COMMAND_FIND_DEVICE = 0x2A;
  static const int COMMAND_AUTO_ANSWER = 0x2B;
  static const int COMMAND_ANC_MODE = 0x2C;
  static const int COMMAND_BLUETOOTH_NAME = 0x2D;
  static const int COMMAND_LED_MODE = 0x2E;
  static const int COMMAND_CLEAR_PAIR_RECORD = 0x2F;
  static const int COMMAND_ANC_GAIN = 0x30;
  static const int COMMAND_TRANSPARENCY_GAIN = 0x31;
  static const int COMMAND_SOUND_EFFECT_3D = 0x32;

  static const int INFO_DEVICE_POWER = 0x01;
  static const int INFO_FIRMWARE_VERSION = 0x02;
  static const int INFO_BLUETOOTH_NAME = 0x03;
  static const int INFO_EQ_SETTING = 0x04;
  static const int INFO_KEY_SETTINGS = 0x05;
  static const int INFO_DEVICE_VOLUME = 0x06;
  static const int INFO_PLAY_STATE = 0x07;
  static const int INFO_WORK_MODE = 0x08;
  static const int INFO_IN_EAR_STATUS = 0x09;
  static const int INFO_LANGUAGE_SETTING = 0x0A;
  static const int INFO_AUTO_ANSWER = 0x0B;
  static const int INFO_ANC_MODE = 0x0C;
  static const int INFO_IS_TWS = 0x0D;
  static const int INFO_TWS_CONNECTED = 0x0E;
  static const int INFO_LED_SWITCH = 0x0F;
  static const int INFO_FW_CHECKSUM = 0x10;
  static const int INFO_ANC_GAIN = 0x11;
  static const int INFO_TRANSPARENCY_GAIN = 0x12;
  static const int INFO_ANC_GAIN_NUM = 0x13;
  static const int INFO_TRANSPARENCY_GAIN_NUM = 0x14;
  static const int INFO_ALL_EQ_SETTINGS = 0x15;
  static const int INFO_MAIN_SIDE = 0x16;
  static const int INFO_PRODUCT_COLOR = 0x17;
  static const int INFO_SOUND_EFFECT_3D = 0x18;
  static const int INFO_DEVICE_CAPABILITIES = 0xFE;
  static const int INFO_MAX_PACKET_SIZE = 0xFF;

  static const Map<int, String> intToNameMap = {
    COMMAND_EQ: 'COMMAND_EQ',
    COMMAND_MUSIC_CONTROL: 'COMMAND_MUSIC_CONTROL',
    COMMAND_KEY: 'COMMAND_KEY',
    COMMAND_AUTO_SHUTDOWN: 'COMMAND_AUTO_SHUTDOWN',
    COMMAND_FACTORY_RESET: 'COMMAND_FACTORY_RESET',
    COMMAND_WORK_MODE: 'COMMAND_WORK_MODE',
    COMMAND_IN_EAR_DETECT: 'COMMAND_IN_EAR_DETECT',
    COMMAND_DEVICE_INFO: 'COMMAND_DEVICE_INFO',
    COMMAND_NOTIFY: 'COMMAND_NOTIFY',
    COMMAND_LANGUAGE: 'COMMAND_LANGUAGE',
    COMMAND_FIND_DEVICE: 'COMMAND_FIND_DEVICE',
    COMMAND_AUTO_ANSWER: 'COMMAND_AUTO_ANSWER',
    COMMAND_ANC_MODE: 'COMMAND_ANC_MODE',
    COMMAND_BLUETOOTH_NAME: 'COMMAND_BLUETOOTH_NAME',
    COMMAND_LED_MODE: 'COMMAND_LED_MODE',
    COMMAND_CLEAR_PAIR_RECORD: 'COMMAND_CLEAR_PAIR_RECORD',
    COMMAND_ANC_GAIN: 'COMMAND_ANC_GAIN',
    COMMAND_TRANSPARENCY_GAIN: 'COMMAND_TRANSPARENCY_GAIN',
    COMMAND_SOUND_EFFECT_3D: 'COMMAND_SOUND_EFFECT_3D',
    INFO_DEVICE_POWER: 'INFO_DEVICE_POWER',
    INFO_FIRMWARE_VERSION: 'INFO_FIRMWARE_VERSION',
    INFO_BLUETOOTH_NAME: 'INFO_BLUETOOTH_NAME',
    INFO_EQ_SETTING: 'INFO_EQ_SETTING',
    INFO_KEY_SETTINGS: 'INFO_KEY_SETTINGS',
    INFO_DEVICE_VOLUME: 'INFO_DEVICE_VOLUME',
    INFO_PLAY_STATE: 'INFO_PLAY_STATE',
    INFO_WORK_MODE: 'INFO_WORK_MODE',
    INFO_IN_EAR_STATUS: 'INFO_IN_EAR_STATUS',
    INFO_LANGUAGE_SETTING: 'INFO_LANGUAGE_SETTING',
    INFO_AUTO_ANSWER: 'INFO_AUTO_ANSWER',
    INFO_ANC_MODE: 'INFO_ANC_MODE',
    INFO_IS_TWS: 'INFO_IS_TWS',
    INFO_TWS_CONNECTED: 'INFO_TWS_CONNECTED',
    INFO_LED_SWITCH: 'INFO_LED_SWITCH',
    INFO_FW_CHECKSUM: 'INFO_FW_CHECKSUM',
    INFO_ANC_GAIN: 'INFO_ANC_GAIN',
    INFO_TRANSPARENCY_GAIN: 'INFO_TRANSPARENCY_GAIN',
    INFO_ANC_GAIN_NUM: 'INFO_ANC_GAIN_NUM',
    INFO_TRANSPARENCY_GAIN_NUM: 'INFO_TRANSPARENCY_GAIN_NUM',
    INFO_ALL_EQ_SETTINGS: 'INFO_ALL_EQ_SETTINGS',
    INFO_MAIN_SIDE: 'INFO_MAIN_SIDE',
    INFO_PRODUCT_COLOR: 'INFO_PRODUCT_COLOR',
    INFO_SOUND_EFFECT_3D: 'INFO_SOUND_EFFECT_3D',
    INFO_DEVICE_CAPABILITIES: 'INFO_DEVICE_CAPABILITIES',
    INFO_MAX_PACKET_SIZE: 'INFO_MAX_PACKET_SIZE',
  };

  int getCommand();
  int getCommandType();
  List<int> getPayload();

  String byteToName(int value) {
    return intToNameMap[value] ?? 'Unknown';
  }
}
